### ISSUE TITLE
'vImageSepConvolve_Planar8' is only available on macOS 11.0 or newer

### ISSUE THREAD

**Issue by kunitoki** [sudara/melatonin_blur#13]
As the title says, if targeting older osx, it's not possible to compile

**Comment by sudara** [comment]
Thanks for reporting.

I couldn't easily find versioning information on Accelerate functions. Did you see any Apple information about this, or is it just the experience you made compiling?

**Comment by sudara** [comment]
![Arc - 2023-11-10 31@2x](https://github.com/sudara/melatonin_blur/assets/472/cc1fd9fc-36bc-4603-8702-879d2ef7ded3)

Ah right, I always forget they are specified this way. Also the header specifies 

```
API_AVAILABLE(macos(11.0), ios(14.0), watchos(7.0), tvos(14.0));
```

I've was always confused about if that was when the function was added to the SDK or where it's currently available. 

Assuming the latter, I'll pick an alternate implementation for < 11.0.

**Comment by sudara** [comment]
I'm targeting 10.13 (High Sierra) and it seems to compile fine. I'll look into adding a runtime check. 

Did you run into problems compiling?

**Comment by asimilon** [comment]
> just not sure how to properly test...

I will need to confirm, but I think I have 10.9 or 10.10 as lowest versions of macOS I still keep on my old Mac Pro just for this kind of scenario.  If I can be of any assistance hit me up.

**Comment by sudara** [comment]
Thanks! I'll ping the issue when I get something to try!

**Comment by kunitoki** [comment]
I'm getting other compilation issues as well, and yes, i've added `Accelerate.framework`
![image](https://github.com/sudara/melatonin_blur/assets/707032/4aa43f8c-b164-4d95-9aa4-3667e6f4d2ae)

**Comment by kunitoki** [comment]
Those seems to be macOS 14.0+

**Comment by sudara** [comment]
Looks like I have some work to do here! Sorry about that, was just working hard on finding the best performing solutions, now I need to work on compatibility, it seems!

**Comment by sudara** [comment]
Probably the route to go is have things fall back to the included Gin implementation at runtime where needed (until i find time to benchmark alternatives).

**Comment by kunitoki** [comment]
I've tried to add `(JUCE_MAC && MAC_OS_X_VERSION_MAX_ALLOWED > MAC_OS_VERSION_13_3)` for those methods but it seems like this doesn't work:
```cpp
    static void argb (const juce::Image& srcImage, juce::Image& dstImage, size_t radius)
    {
        jassert (srcImage.getFormat() == juce::Image::PixelFormat::ARGB);
#if (JUCE_MAC && MAC_OS_X_VERSION_MAX_ALLOWED > MAC_OS_VERSION_13_3) || JUCE_IOS
        auto kernel = createFloatKernel (radius);

        const auto w = (unsigned int) srcImage.getWidth();
        const auto h = (unsigned int) srcImage.getHeight();
        juce::Image::BitmapData srcData (srcImage, juce::Image::BitmapData::readWrite);
        juce::Image::BitmapData dstData (dstImage, juce::Image::BitmapData::readWrite);

        // vImageSepConvolve isn't happy operating in-place
        vImage_Buffer src = { srcData.getLinePointer (0), h, w, (size_t) srcData.lineStride };
        vImage_Buffer dst = { dstData.getLinePointer (0), h, w, (size_t) dstData.lineStride };
        vImageSepConvolve_ARGB8888 (&src, &dst, nullptr, 0, 0, kernel.data(), (unsigned int) kernel.size(), kernel.data(), (unsigned int) kernel.size(), 0, Pixel_8888 { 0, 0, 0, 0 }, kvImageEdgeExtend);
#else
        stackBlur::ginRGBA (img, radius); // There seems to be missing a non in-place blur in gin
#endif
```

**Comment by kunitoki** [comment]
> Probably the route to go is have things fall back to the included Gin implementation at runtime where needed (until i find time to benchmark alternatives).

Or provide a good simd convolution alternative.

**Comment by sudara** [comment]
> Or provide a good simd convolution alternative.

There are couple people interested in building SIMD variations of the vector implementation, so  I'm betting this will happen!

**Comment by sudara** [comment]
Ok, I have a draft implementation to make all the vImage stuff conditional at both compile and run time https://github.com/sudara/melatonin_blur/pull/16

I'm going to have to get #6 done first before merging, to ensure it's happy on at least macOS 11/12/13 and Windows. Don't want any more breakage!

**Comment by sudara** [comment]
@kunitoki You should be good to go, I merged the compatibility changes in #16.

I still would like to see some evidence that the runtime checks are needed (i.e. if i can compile vImageSepConvolve on one machine, will it work on earlier targets before the API was available?) but I went the conservative route for now.

#19 and #20 are both followups for the compatibility work. Off to ADC now though!

**Comment by kmolcard** [comment]
Hello, I'm trying to compile on 10.14.6 mac Intel Xcode 11.3.1 and got the following compile error:
vImage.h:44:9: error: use of undeclared identifier 'vImageSepConvolve_Planar8'

Just to be sure, can you confirm you only want to target macOS 11+?

**Comment by kunitoki** [comment]
![image](https://github.com/sudara/melatonin_blur/assets/707032/14777c7e-da1f-45c1-8740-46f9c23b5aff)
Still getting this warning on ee269d3

**Comment by sudara** [comment]
Thx — I meant to ask, is this on a Projucer project, exported to xcode?

**Comment by kunitoki** [comment]
Yes

**Comment by sudara** [comment]
#53 should handle those warnings still showing up (despite being guarded at runtime)
